name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make executable
      run: chmod +x test_suite/ci.sh test_suite/gui_test.exp
    - name: ci
      run: ./test_suite/ci.sh
